server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userregistration
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
# Java mail properties
  mail:
    host: localhost
    port: 1025
    username: habay
    password: habay
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000


#  security:
#    oauth2:
#      client:
#        registration:
#          api-client-oidc:
#            provider: spring
#            client-id: api-client
#            client-secret: secret
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
#            scope: openid
#            client-name: api-client-oidc
#          api-client-authorization-code:
#            provider: spring
#            client-id: api-client
#            client-secret: secret
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://127.0.0.1:8080/authorized"
#            scope: api.read
#            client-name: api-client-authorization-code
#        provider:
#          spring:
#            issuer-uri: http://auth-server:9000
